/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as EmbassiesRouteImport } from './routes/embassies'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SurakshaAiRouteImport } from './routes/suraksha-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassiesRoute = EmbassiesRouteImport.update({
  id: '/embassies',
  path: '/embassies',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SurakshaAiRoute = SurakshaAiRouteImport.update({
  id: '/suraksha-ai',
  path: '/suraksha-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/check-in': typeof CheckInRoute
  '/embassies': typeof EmbassiesRoute
  '/family': typeof FamilyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/suraksha-ai': typeof SurakshaAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/check-in': typeof CheckInRoute
  '/embassies': typeof EmbassiesRoute
  '/family': typeof FamilyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/suraksha-ai': typeof SurakshaAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/check-in': typeof CheckInRoute
  '/embassies': typeof EmbassiesRoute
  '/family': typeof FamilyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/suraksha-ai': typeof SurakshaAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/check-in'
    | '/embassies'
    | '/family'
    | '/map'
    | '/profile'
    | '/sos'
    | '/suraksha-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/check-in'
    | '/embassies'
    | '/family'
    | '/map'
    | '/profile'
    | '/sos'
    | '/suraksha-ai'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/check-in'
    | '/embassies'
    | '/family'
    | '/map'
    | '/profile'
    | '/sos'
    | '/suraksha-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  CheckInRoute: typeof CheckInRoute
  EmbassiesRoute: typeof EmbassiesRoute
  FamilyRoute: typeof FamilyRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SosRoute: typeof SosRoute
  SurakshaAiRoute: typeof SurakshaAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassies': {
      id: '/embassies'
      path: '/embassies'
      fullPath: '/embassies'
      preLoaderRoute: typeof EmbassiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suraksha-ai': {
      id: '/suraksha-ai'
      path: '/suraksha-ai'
      fullPath: '/suraksha-ai'
      preLoaderRoute: typeof SurakshaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  CheckInRoute: CheckInRoute,
  EmbassiesRoute: EmbassiesRoute,
  FamilyRoute: FamilyRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SosRoute: SosRoute,
  SurakshaAiRoute: SurakshaAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
